/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eLifeGame;

import env.Environment;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Environment classUnderTest = new Environment();
        assertNotNull(classUnderTest.toString(), "app should have a greeting");
    }
}
